{% set name = "mattspy" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/beckermr/mattspy/archive/refs/tags/{{ version }}.tar.gz
  sha256: caba33eed2e05aaee118ada3f4d71a73495ca99db2890b098c76cb6e1dce9218

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mattspy-exec-run-pickled-task = mattspy.mattspy_exec_run:run_pickled_task

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm <6.1
    - setuptools_scm_git_archive
  run:
    - python >=3.7
    - cloudpickle
    - numpy
    - joblib
    - importlib_metadata
    - loky

test:
  imports:
    - mattspy
  commands:
    - command -v mattspy-exec-run-pickled-task

about:
  home: https://github.com/beckermr/mattspy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: my personal python utils

extra:
  recipe-maintainers:
    - beckermr
