{% set name = "mattspy" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/beckermr/mattspy/archive/refs/tags/{{ version }}.tar.gz
  sha256: e990838845ff5a4662a77a08719fff99f5e03b3a49add4192b259eb2538e80ab

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mattspy-exec-run-pickled-task = mattspy.mattspy_exec_run:run_pickled_task

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.7
    - cloudpickle
    - numpy
    - joblib
    - importlib_metadata
    - loky
    - scipy
    - esutil

test:
  imports:
    - mattspy
  commands:
    - command -v mattspy-exec-run-pickled-task

about:
  home: https://github.com/beckermr/mattspy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: my personal python utils

extra:
  recipe-maintainers:
    - beckermr
