{% set name = "mattspy" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/beckermr/mattspy/archive/refs/tags/{{ version }}.tar.gz
  sha256: f1e4e065a82b63a6f1573e59d943f68306a5aefd7225566d8a27768942be85ed

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mattspy-exec-run-pickled-task = mattspy.mattspy_exec_run:run_pickled_task

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm <6.1
    - setuptools_scm_git_archive
  run:
    - python >=3.7
    - cloudpickle
    - numpy
    - joblib
    - importlib_metadata

test:
  imports:
    - mattspy
  commands:
    - command -v mattspy-exec-run-pickled-task

about:
  home: https://github.com/beckermr/mattspy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: my personal python utils

extra:
  recipe-maintainers:
    - beckermr
