{% set name = "mattspy" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/beckermr/mattspy/archive/refs/tags/{{ version }}.tar.gz
  sha256: 1369466e76e11fb2d76312c2bfd6d4440cec13f853e41b19c74d910e53249bd7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mattspy-exec-run-pickled-task = mattspy.mattspy_exec_run:run_pickled_task

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.7
    - cloudpickle
    - numpy
    - joblib
    - importlib_metadata
    - loky

test:
  imports:
    - mattspy
  commands:
    - command -v mattspy-exec-run-pickled-task

about:
  home: https://github.com/beckermr/mattspy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: my personal python utils

extra:
  recipe-maintainers:
    - beckermr
